(println "Five Numbers That Don't Match:")
(println(float(/ 25 26)))
(println(float(/ 6 17)))
(println(float(/ 7 29)))
(println(float(/ 5 53)))
(println(float(/ 7 47)))
(println "Five Numbers That Do Match:")
(println(float(/ 1 2)))
(println(float(/ 6 24)))
(println(float(/ 1 40)))
(println(float(/ 3 100)))
(println(float(/ 5 25)))

(def n (count "Facetiously speaking, what is special about May the fourth?"))
(def k 3)
;(println (double(* n (factorial (dec n))) (* (n - k) (factorial (dec n)))))))
(println 195054)